apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: devportal
  description: An example of a Backstage application.
  # Example for optional annotations
  annotations:
    jenkins.io/job-full-name: "job-name"
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
